---
- hosts: all
  tasks:
    - name: get the date
      command: "date"
      register: current_date

    - name: pause for random time
      pause:
        seconds: "{{ 1 | random }}"

    - name: randomly fail
      fail:
        msg: "eeek we failed"
      when: 10 | random > 5

    - name: debug date
      debug:
        var: current_date.stdout
